title: FarmBot Software Documentation
url: https://software.farm.bot
description: Learn how to set up, use, and modify FarmBot software
logo: /assets/images/documentation.png
theme: jekyll-theme-cayman
remote_theme: FarmBot-Docs/farmbot-theme@main
baseurl: /
color: '#316318'
latest_version_number: 12
plugins:
  - jemoji
  - jekyll-redirect-from
  - jekyll-remote-theme
include:
  - _images
  - _redirects
exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - vendor
